### ISSUE TITLE
{} => do\end not working correctly

### ISSUE THREAD

**Issue by arthurkarganyanekleft** [jgdavey/vim-blockle#10]
Hi! do\end => {} works perfect, but {} => do\end generates
from
```  
    let(:service) { IncrementService.new(request, basket, article) }
```
this:
```  
    let(:service) {do
      IncrementService.new(request, basket, article
    end }
```

**Comment by 5t111111** [comment]
I've encountered the same issue, so I've tried the below different versions of Vim, but `{} => do\end` doesn't work correctly on both Vim.

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 28 2015 19:46:19)
Compiled by root@apple.com
```

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  6 2016 13:20:05)
MacOS X (unix) version
Included patches: 1-1817
Compiled by Homebrew
```

Strangely enough, this problem doesn't occur on neovim so far.

```
NVIM 0.1.4
```

**Comment by 5t111111** [comment]
@arthurkarganyanekleft After some investigation, I've found the cause of the problem.

Although vim-blockle tries to find the `end` keyword corresponding to `do` by invoking the `%` command, but Vim cannot find it wihout `matchit`.

So, the solution for me was:

Simply add either of one of the followings in `.vimrc`.

```vim
source $VIMRUNTIME/macros/matchit.vim
```

```vim
runtime macros/matchit.vim
```

Hope this helps you.
