### ISSUE TITLE
{} <=> do/end not working

### ISSUE THREAD

**Issue by Sathors** [jgdavey/vim-blockle#11]
With VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  2 2016 05:21:06),

```ruby
my_method do |param|
  something param
end
```
gives me
```ruby
my_method { |param| something param  w} end
```
whatever the position of the cursor.

```ruby
my_method { |param| something param }
```
gives me
```ruby
my_method {
  endo |var| assert @registration.registered? }
```

I also tried with an empty .vimrc and .vim (with only blockle), it does not work neither.

Thanks for your help!

**Comment by jgdavey** [comment]
This seems like `matchit` is either missing or outdated.
