### ISSUE TITLE
begin/end --> {} doesn't work

### ISSUE THREAD

**Issue by joker-777** [jgdavey/vim-blockle#5]
Hi 

I've got this line

```ruby
before { FactoryGirl.create(:identity_provider, email: 'bla@test.com' }
```

converting it to 

```ruby
before do
  FactoryGirl.create(:identity_provider, email: 'bla@test.com'
end
```

works fine but converting it back results in

```ruby
before {.create(:identity_provider, email: 'bla@test.com')
end
```

any ideas why?

**Comment by tscheffe** [comment]
I'm having the same issue. I will look into `splitjoin` as suggested, so feel free to ignore, but here's further info (with vimrc) for debugging.

[.vimrc here](https://github.com/tscheffe/dotfiles/blob/97745540e8df58f453ff56103fd2ea5756aed3c9/.vimrc) I don't think it's a plugin issue, I disabled all but `blockle` and still had the issue.

With
```ruby
    subject(:perform) { IcsBuilder.update(create.to_ics, start_time: new_start_time, end_time: new_end_time) }
```
toggling works, on either on either bracket and inside the brackets it will correctly toggle to:

```ruby
    subject(:perform) do
      IcsBuilder.update(create.to_ics, start_time: new_start_time, end_time: new_end_time)
    end
```

Toggling from `do` or anywhere in the block always results in:
```ruby
    subject(:perform) {.update(create.to_ics, start_time: new_start_time, end_time: new_end_time)
    end
```

Toggling from cursor on or in `end` goes from:
```ruby
    subject(:perform) do
      IcsBuilder.update(create.to_ics, start_time: new_start_time, end_time: new_end_time)
    end

    context 'the first update' do
```
to
```ruby
    subject(:perform) do
      IcsBuilder.update(create.to_ics, start_time: new_start_time, end_time: new_end_time)
    { 'the first update' do
```

It sort of feels like an off-by-one error, in that it's either deleting `create` and leaving up `end` or it's ignoring the intended block and toggling the next one (incorrectly).

Hope that helps!

**Comment by jgdavey** [comment]
As noted before, many issues are caused if `matchit` has not been loaded *before* blockle.
