### ISSUE TITLE
Bangs leave trailing space

### ISSUE THREAD

**Issue by cvincent** [jgdavey/vim-blockle#8]
With the following:

```
asdf.each do |a|
  a.stuff!
end
```

Converts to this ("•" denotes the extra space):

```
asdf.each { |a| a.stuff!• }
```

And then back to this (notice the "•"):

```
asdf.each do |a|
  a.stuff!•
end
```

**Comment by jgdavey** [comment]
I can reproduce this, but haven't gotten around to looking into fixing it.

**Comment by jgdavey** [comment]
Closing this since I'm archiving the project.
